language: node_js
node_js:
  - "6.10.3"
before_install:
  - nvm install 6.10.3
  - nvm use 6.10.3
deploy:
  provider: s3
  access_key_id: $key
  secret_access_key:
    secure: $secret
  bucket: "cararust.com"
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  local_dir: dist
